const ACTION_CONSTANTS = {
  INIT_TASK_LIST: "INIT_TASK_LIST",
  ADD_NEW_TASK: "ADD_NEW_ITEM",
  UPDATE_TASK_TEXT: "UPDATE_ADD_ITEM_TEXT",
  TOGGLE_TASK_STATUS: "TOGGLE_ITEM",
  REMOVE_TASK: "REMOVE_ITEM",
  LOAD_STORE: "LOAD_STORE",
  APPLY_FILTER: "APPLY_FILTER",
  TOGGLE_DRAWER: "TOGGLE_DRAWER",
  UPDATE_TASK_DATE: "UPDATE_TASK_DATE"
};

export default ACTION_CONSTANTS;

export const STYLE_CONSTANTS = {
  drawerWidth: 240
};
